import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
// import { ThemeProvider } from "./theme-provider";

const ibmPlex = IBM_Plex_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* extra attributes frrom style, class error | https://github.com/shadcn-ui/ui/issues/1906 */}
      <body className={ibmPlex.className}>
        {/* below item generates warning in browser console */}
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableColorScheme
          disableTransitionOnChange
        > */}
        <main>{children}</main>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
